/**
 * Generates supabase/seed/seed.sql. Deterministic: the same run always produces
 * the same file, so a diff in the seed is a real change and not noise.
 *
 *   node supabase/seed/generate.mjs > supabase/seed/seed.sql
 */

const AREAS = [
  ['Roma Norte, CDMX', 19.42, -99.16],
  ['Condesa, CDMX', 19.41, -99.18],
  ['Del Valle, CDMX', 19.38, -99.16],
  ['Coyoacán, CDMX', 19.35, -99.16],
  ['Narvarte, CDMX', 19.39, -99.15],
  ['Escandón, CDMX', 19.4, -99.19],
  ['Santa Fe, CDMX', 19.36, -99.26],
  ['Azcapotzalco, CDMX', 19.48, -99.18],
  ['Iztapalapa, CDMX', 19.36, -99.06],
  ['Satélite, Edomex', 19.51, -99.23],
];

const INTERESTS = [
  'cine', 'series', 'libros', 'museos', 'musica-en-vivo', 'teatro', 'cafe', 'cocinar',
  'juegos-de-mesa', 'videojuegos', 'caminatas', 'ciclismo', 'correr', 'senderismo',
  'natacion', 'gimnasio', 'yoga', 'meditacion', 'fotografia', 'dibujo', 'escritura',
  'musica-tocar', 'idiomas', 'tecnologia', 'ciencia', 'emprender', 'voluntariado',
  'mascotas', 'jardineria', 'viajes',
];

const INTENTIONS = [
  'close_friendship', 'casual_meetups', 'activity_partner', 'expand_circle',
  'new_in_city', 'language_practice', 'similar_life_stage',
];

const ENERGY = ['calm', 'mixed', 'active'];
const WARM_UP = ['needs_time', 'in_between', 'opens_quickly'];
const GROUPS = ['one_on_one', 'small_group', 'flexible', 'many_people'];
const FREQUENCY = ['daily', 'few_times_week', 'weekly', 'occasional'];
const STYLES = ['long_messages', 'short_messages', 'voice_notes', 'meet_soon'];
const SPONTANEITY = ['plans_ahead', 'flexible', 'spontaneous'];
const PLANS = ['calm', 'mixed', 'active'];
const ALCOHOL = ['no_preference', 'prefers_alcohol_free', 'fine_with_alcohol'];
const BLOCKS = ['morning', 'afternoon', 'evening'];

const NAMES = [
  'Ana', 'Beto', 'Caro', 'Diego', 'Elena', 'Fer', 'Gabriela', 'Hugo', 'Irene', 'Javier',
  'Karla', 'Luis', 'Mariana', 'Nico', 'Olivia', 'Pablo', 'Quetzalli', 'Rocío', 'Samuel',
  'Tania', 'Ulises', 'Valeria', 'Wendy', 'Ximena', 'Yamil', 'Zoe', 'Andrés', 'Bruno',
  'Cecilia', 'Damián', 'Estela', 'Fabián',
];

const BIOS = [
  'Me mudé hace cuatro meses y sigo aprendiendo la ciudad. Busco gente para caminar sin prisa y terminar en un café.',
  'Trabajo de noche, así que mis planes suelen ser entre semana. Prefiero conversaciones largas antes que salir cada fin.',
  'Vengo de un pueblo pequeño y aquí todo va rápido. Me cuesta el primer mensaje, pero después no me callo.',
  'Padre de familia con poco tiempo libre. Busco un par de personas para ver cine o jugar algo los domingos.',
  'Salgo mucho, pero casi siempre con la misma gente. Quiero ampliar el círculo sin sentir que estoy en una entrevista.',
  'Me gusta cocinar para otros. Si aparece alguien que quiera probar recetas raras, mejor.',
  'Estoy retomando el ejercicio después de un año difícil. Ir acompañada me ayuda a no abandonar.',
  'Estudio de nuevo a los 38. Busco gente en una etapa parecida, sin prisa por ser mejores amigos en una semana.',
  'Trabajo remoto y hablo con mi laptop todo el día. Necesito planes tranquilos con gente real.',
  'Recién salí de una relación larga y mi círculo se redujo mucho. Voy con calma y con honestidad.',
];

const BOUNDARIES = [
  'Nada de coqueteo, vengo por amistad.',
  'Prefiero conocer en lugares públicos las primeras veces.',
  'No comparto mi dirección ni mi teléfono al inicio.',
  'Respondo con calma: a veces tardo un día.',
  'No me interesan planes con mucho alcohol.',
];

const TOPICS = [
  'películas que nadie vio', 'series de época', 'comida callejera', 'música en vinilo',
  'viajes baratos', 'plantas de interior', 'historia de la ciudad', 'tecnología y privacidad',
];

const WANTS = [
  'ir a una obra de teatro', 'probar escalada', 'hacer una caminata larga',
  'ir a un mercado de barrio', 'tomar un taller de cerámica', 'ver un partido en vivo',
];

// Deterministic RNG so every run produces byte-identical output.
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const random = rng(20260802);
const pick = (list) => list[Math.floor(random() * list.length)];
const pickMany = (list, count) => {
  const copy = [...list];
  const out = [];
  for (let i = 0; i < count && copy.length > 0; i += 1) {
    out.push(copy.splice(Math.floor(random() * copy.length), 1)[0]);
  }
  return out;
};

const uuid = (n) => {
  const hex = n.toString(16).padStart(12, '0');
  return `00000000-0000-4000-8000-${hex}`;
};

const quote = (value) => `'${String(value).replaceAll("'", "''")}'`;
const arrayLiteral = (values) => `array[${values.map(quote).join(', ')}]`;

const lines = [];
const say = (line = '') => lines.push(line);

say('-- Generated by supabase/seed/generate.mjs — do not edit by hand.');
say('-- Demo data for local development. Never load this into production.');
say('--');
say('-- Demo accounts (password for all of them: demo-circulo-2026):');
say('--   ana@demo.circulo.app     — perfil completo, con matches y conversación');
say('--   beto@demo.circulo.app    — match con Ana');
say('--   caro@demo.circulo.app    — sin matches todavía, buena para probar descubrimiento');
say('--   nuevo@demo.circulo.app   — onboarding incompleto');
say('--   mod@demo.circulo.app     — moderador');
say('--   admin@demo.circulo.app   — administrador');
say('');
say('begin;');
say('');
say('-- Password for every seeded account: demo-circulo-2026');
say("-- Hashed here with pgcrypto so these accounts can sign in immediately after");
say('-- `supabase db reset`, with no separate Admin API step (and no risk of that step');
say('-- silently no-opping against a user auth.users already has, which is what an');
say("-- `insert ... on conflict do nothing` followed by a separate password-setting");
say('-- call would do).');
say('');
say("select set_config('circulo.demo_password_hash', crypt('demo-circulo-2026', gen_salt('bf')), true);");
say('');

const users = [];
const totalProfiles = 32;

for (let i = 0; i < totalProfiles; i += 1) {
  const id = uuid(i + 1);
  const name = NAMES[i % NAMES.length];
  const email = `${name.toLowerCase().normalize('NFD').replace(/[^a-z]/g, '')}${i}@demo.circulo.app`;
  const [areaLabel, lat, lon] = AREAS[i % AREAS.length];
  const age = 19 + Math.floor(random() * 30);
  const birthYear = 2026 - age;
  const intentionCount = 1 + Math.floor(random() * 2);
  const interestCount = 3 + Math.floor(random() * 5);
  const slotCount = 2 + Math.floor(random() * 4);

  const slots = [];
  while (slots.length < slotCount) {
    const slot = `${Math.floor(random() * 7)}:${pick(BLOCKS)}`;
    if (!slots.includes(slot)) slots.push(slot);
  }

  users.push({
    id,
    email,
    name,
    birthDate: `${birthYear}-0${1 + (i % 9)}-1${i % 10}`,
    areaLabel,
    lat,
    lon,
    bio: BIOS[i % BIOS.length],
    intentions: pickMany(INTENTIONS, intentionCount),
    interests: pickMany(INTERESTS, interestCount),
    languages: random() > 0.6 ? ['es', 'en'] : ['es'],
    slots,
    social: {
      energy: pick(ENERGY),
      warmUp: pick(WARM_UP),
      group: pick(GROUPS),
      frequency: pick(FREQUENCY),
      styles: pickMany(STYLES, 1 + Math.floor(random() * 2)),
      spontaneity: pick(SPONTANEITY),
      plans: pick(PLANS),
      alcohol: pick(ALCOHOL),
    },
    maxDistance: [10, 15, 25, 40, 60][Math.floor(random() * 5)],
    minAge: 18 + Math.floor(random() * 4) * 3,
    maxAge: 45 + Math.floor(random() * 5) * 6,
    boundaries: pickMany(BOUNDARIES, 1 + Math.floor(random() * 2)),
    topics: pickMany(TOPICS, 2),
    wants: pickMany(WANTS, 2),
    // A few incomplete profiles on purpose: the app must handle them.
    complete: i % 11 !== 10,
  });
}

// Named demo accounts keep stable emails so the README can document them.
users[0].email = 'ana@demo.circulo.app';
users[1].email = 'beto@demo.circulo.app';
users[2].email = 'caro@demo.circulo.app';
users[0].intentions = ['new_in_city', 'close_friendship'];
users[1].intentions = ['new_in_city', 'expand_circle'];
users[0].interests = ['cine', 'cafe', 'caminatas', 'libros'];
users[1].interests = ['cine', 'cafe', 'museos', 'fotografia'];
users[0].slots = ['6:afternoon', '0:morning', '3:evening'];
users[1].slots = ['6:afternoon', '0:morning', '5:evening'];
users[0].languages = ['es', 'en'];
users[1].languages = ['es', 'en'];

const staff = [
  { id: uuid(900), email: 'mod@demo.circulo.app', role: 'moderator' },
  { id: uuid(901), email: 'admin@demo.circulo.app', role: 'admin' },
];

const incomplete = { id: uuid(910), email: 'nuevo@demo.circulo.app' };

say('-- --- auth users ---------------------------------------------------------');
say('-- A fully-formed row, not just id + email: GoTrue needs aud/role set to');
say("-- 'authenticated' and email_confirmed_at set, or it treats the account as");
say('-- unconfirmed and refuses password sign-in.');
for (const user of [...users, ...staff, incomplete]) {
  say(
    `insert into auth.users (` +
      `instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, ` +
      `raw_app_meta_data, raw_user_meta_data, created_at, updated_at, ` +
      `confirmation_token, recovery_token, email_change_token_new, email_change` +
      `) values (` +
      `'00000000-0000-0000-0000-000000000000', ${quote(user.id)}, 'authenticated', 'authenticated', ` +
      `${quote(user.email)}, current_setting('circulo.demo_password_hash', true), now(), ` +
      `'{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), ` +
      `'', '', '', ''` +
      `) on conflict (id) do nothing;`,
  );
  say(
    `insert into auth.identities (id, user_id, provider_id, provider, identity_data, created_at, updated_at) values (` +
      `gen_random_uuid(), ${quote(user.id)}, ${quote(user.id)}, 'email', ` +
      `jsonb_build_object('sub', ${quote(user.id)}::text, 'email', ${quote(user.email)}), now(), now()` +
      `) on conflict (provider_id, provider) do nothing;`,
  );
}
say('');

say('insert into staff_members (user_id, role) values');
say(staff.map((s) => `  (${quote(s.id)}, ${quote(s.role)})`).join(',\n') + '\non conflict (user_id) do nothing;');
say('');

say('-- --- profiles -----------------------------------------------------------');
for (const user of users) {
  say(
    `insert into profiles (id, display_name, birth_date, area_label, lat, lon, bio, boundaries, conversation_topics, wants_to_try) values (` +
      `${quote(user.id)}, ${quote(user.name)}, ${quote(user.birthDate)}, ${quote(user.areaLabel)}, ` +
      `${user.lat}, ${user.lon}, ${quote(user.bio)}, ${arrayLiteral(user.boundaries)}, ` +
      `${arrayLiteral(user.topics)}, ${arrayLiteral(user.wants)}) on conflict (id) do nothing;`,
  );
  say(
    `insert into profile_preferences (user_id, max_distance_km, min_age, max_age) values (` +
      `${quote(user.id)}, ${user.maxDistance}, ${user.minAge}, ${Math.max(user.minAge, user.maxAge)}) on conflict (user_id) do nothing;`,
  );
  say(
    `insert into social_preferences (user_id, social_energy, warm_up_speed, group_preference, contact_frequency, communication_styles, spontaneity, plan_preference, alcohol_preference) values (` +
      `${quote(user.id)}, ${quote(user.social.energy)}, ${quote(user.social.warmUp)}, ${quote(user.social.group)}, ` +
      `${quote(user.social.frequency)}, array[${user.social.styles.map(quote).join(', ')}]::communication_style[], ` +
      `${quote(user.social.spontaneity)}, ${quote(user.social.plans)}, ${quote(user.social.alcohol)}) on conflict (user_id) do nothing;`,
  );
  say(
    `insert into user_friendship_intentions (user_id, intention) values ` +
      user.intentions.map((intention) => `(${quote(user.id)}, ${quote(intention)})`).join(', ') +
      ' on conflict do nothing;',
  );
  say(
    `insert into user_interests (user_id, interest_slug) values ` +
      user.interests.map((slug) => `(${quote(user.id)}, ${quote(slug)})`).join(', ') +
      ' on conflict do nothing;',
  );
  say(
    `insert into user_languages (user_id, language_code) values ` +
      user.languages.map((code) => `(${quote(user.id)}, ${quote(code)})`).join(', ') +
      ' on conflict do nothing;',
  );
  say(
    `insert into availability_slots (user_id, weekday, block) values ` +
      user.slots
        .map((slot) => {
          const [weekday, block] = slot.split(':');
          return `(${quote(user.id)}, ${weekday}, ${quote(block)})`;
        })
        .join(', ') +
      ' on conflict do nothing;',
  );
  if (user.complete) {
    say(
      `insert into profile_photos (user_id, storage_path, position, moderation_status) values (` +
        `${quote(user.id)}, ${quote(`${user.id}/main.jpg`)}, 0, 'approved') on conflict do nothing;`,
    );
  }
  say('');
}

say('-- Profile with onboarding started but not finished: the app must not show it');
say('-- in discovery and must resume onboarding when the user signs in.');
say(
  `insert into profiles (id, display_name, birth_date, area_label, lat, lon) values (` +
    `${quote(incomplete.id)}, 'Nuevo', '1998-03-04', 'Tacubaya, CDMX', 19.4, -99.19) on conflict (id) do nothing;`,
);
say(`insert into profile_preferences (user_id) values (${quote(incomplete.id)}) on conflict do nothing;`);
say(`insert into social_preferences (user_id) values (${quote(incomplete.id)}) on conflict do nothing;`);
say(
  `insert into onboarding_progress (user_id, step, completed_steps) values (` +
    `${quote(incomplete.id)}, 'interests', array['identity', 'photos', 'bio']) on conflict do nothing;`,
);
say('');

say('-- --- connections --------------------------------------------------------');
say('-- Ana and Beto: mutual interest, a match and a short conversation.');
const [ana, beto, caro] = users;
const pairs = [
  [ana, beto],
  [users[3], users[4]],
  [users[5], users[6]],
];

for (const [a, b] of pairs) {
  say(
    `insert into profile_decisions (actor_id, target_id, decision, idempotency_key) values ` +
      `(${quote(a.id)}, ${quote(b.id)}, 'interested', gen_random_uuid()), ` +
      `(${quote(b.id)}, ${quote(a.id)}, 'interested', gen_random_uuid()) on conflict do nothing;`,
  );
  const low = a.id < b.id ? a.id : b.id;
  const high = a.id < b.id ? b.id : a.id;
  say(
    `insert into matches (user_low, user_high) values (${quote(low)}, ${quote(high)}) on conflict do nothing;`,
  );
  say(
    `insert into conversations (match_id) select id from matches where user_low = ${quote(low)} and user_high = ${quote(high)} on conflict do nothing;`,
  );
  say(
    `insert into conversation_members (conversation_id, user_id) ` +
      `select c.id, m.user_low from conversations c join matches m on m.id = c.match_id where m.user_low = ${quote(low)} and m.user_high = ${quote(high)} ` +
      `union all select c.id, m.user_high from conversations c join matches m on m.id = c.match_id where m.user_low = ${quote(low)} and m.user_high = ${quote(high)} on conflict do nothing;`,
  );
}
say('');

const conversationLookup = (low, high) =>
  `(select c.id from conversations c join matches m on m.id = c.match_id where m.user_low = ${quote(low)} and m.user_high = ${quote(high)})`;
const anaLow = ana.id < beto.id ? ana.id : beto.id;
const anaHigh = ana.id < beto.id ? beto.id : ana.id;

const conversation = [
  [ana.id, 'Hola Beto. Vi que también acabas de mudarte, ¿de dónde llegaste?'],
  [beto.id, 'Hola Ana. De Guadalajara, hace tres meses. Sigo sin entender el metro.'],
  [ana.id, 'Te entiendo. ¿Te laten los domingos por la mañana para caminar por Chapultepec?'],
  [beto.id, 'Sí, ese horario me funciona. ¿El domingo que viene?'],
];

for (const [sender, body] of conversation) {
  say(
    `insert into messages (conversation_id, sender_id, body) values (${conversationLookup(anaLow, anaHigh)}, ${quote(sender)}, ${quote(body)});`,
  );
}
say('');
say(
  `insert into match_feedback (match_id, author_id, feedback) select m.id, ${quote(ana.id)}, 'we_talked' from matches m where m.user_low = ${quote(anaLow)} and m.user_high = ${quote(anaHigh)} on conflict do nothing;`,
);
say('');

say('-- --- safety -------------------------------------------------------------');
say('-- One block, one open report and one already-resolved report, so the admin');
say('-- panel has something to show on first run.');
say(
  `insert into blocks (blocker_id, blocked_id) values (${quote(caro.id)}, ${quote(users[7].id)}) on conflict do nothing;`,
);
say(
  `insert into reports (reporter_id, reported_user_id, category, details, status) values ` +
    `(${quote(caro.id)}, ${quote(users[7].id)}, 'persistent_romantic_intent', 'Insistió con mensajes románticos después de pedirle que parara.', 'open'), ` +
    `(${quote(users[8].id)}, ${quote(users[9].id)}, 'spam', 'Envió el mismo enlace a varias personas.', 'open'), ` +
    `(${quote(users[10].id)}, ${quote(users[11].id)}, 'harassment', 'Comentarios agresivos tras un pase.', 'dismissed');`,
);
say('');
say(
  `insert into account_flags (user_id, flag, reason) values (${quote(users[9].id)}, 'spam', 'Patrón de mensajes idénticos.') on conflict do nothing;`,
);
say('');

say('-- --- discovery history ---------------------------------------------------');
say('-- Impressions so the exposure fairness rules have something to work with.');
say(
  `insert into profile_impressions (viewer_id, shown_user_id) select ${quote(caro.id)}, id from profiles where id <> ${quote(caro.id)} limit 12;`,
);
say('');

say('-- Recompute completeness for every seeded profile.');
say('select recompute_profile_complete(id) from profiles;');
say('');
say('commit;');

process.stdout.write(lines.join('\n') + '\n');
